version: '3'
services: 
  postgres:
    container_name: 'postgres'
    image: postgres:9.4
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data
